### ISSUE TITLE
UploadApi: conflict between upload_file and content

### ISSUE THREAD

**Issue by sjwelling** [ClickSend/clicksend-perl#2]
There is a bug in the uploads_post call. According to your Postman example (which works), the uploads_post() call should have a 'content' and a 'convert' component. However, UploadApi.pm says that 'upload_file' is a required parameter.

From the sample code in https://developers.clicksend.com/docs/rest/v3/?perl#ClickSend-v3-API-Upload:
```
my $json_output = $api->uploads_post('content' => $content ,'convert' => 'fax');
```
The resulting error is: ```Missing the required parameter 'upload_file' when calling uploads_post```

If you change all instances of ```upload_file``` in UploadApi.pm to ```content```, then you get this error:

```
API Exception(400): Bad Request Please provide valid content first.
```
I think you have a misnamed variable or something.

**Comment by Jaxom-ClickSend** [comment]
The generator has been updated to use the correct variable name, thank you for notifying us of the issue.
